### ISSUE TITLE
Wishlish Option Error: Failed to execute script 'main' due to unhandled exception!

### ISSUE THREAD

**Issue by baltimoresports** [PalmaLuv/SteamGiftBot#12]
> Traceback (most recent call last):
>   File "main.py", line 53, in <module>
>   File "main.py", line 49, in run
>   File "method\method.py", line 140, in start
>     self.getGameContent()
>   File "method\method.py", line 91, in getGameContent
>     filtered_url = self.filterURL[self.type] % _page
> KeyError: 'Wishlist'
> [11924] Failed to execute script 'main' due to unhandled exception!

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1420685/221358780-b8756ff3-9533-4d44-a6d0-b5894c2bf9a5.png">

**Comment by PalmaLuv** [comment]
I apologize for such a mistake, to fix it in the file `main.py`, line [40](https://github.com/PalmaLuv/SteamGiftBot/blob/5fd262904ba8a0e3b6f7e261faac3acdcb40a894/main.py#L40), you need to correct the value
![image](https://user-images.githubusercontent.com/84909252/221368198-42c20dbd-1343-4d9f-bef8-5bcc1aa154bc.png)

To fix the error, change `'Wishlist
` to `'WishList'`
I will add the `*.exe` files later

Or is there an alternative solution, this change in the file `info.json`, `WishList` to `Wishlist`

**Comment by baltimoresports** [comment]
The info.json fix worked great. Much appreciated!
